import { ethers } from 'ethers';
// You would typically import the ABI from the artifacts generated by Hardhat
// import VotingArtifact from '../../../smart-contract/artifacts/contracts/Voting.sol/Voting.json';

// Placeholder ABI for now (ideally copy from artifacts)
const VotingABI = [
    "function addCandidate(string memory _name) public",
    "function setElectionState(bool _state) public",
    "function vote(uint _candidateId) public",
    "function getAllCandidates() public view returns (tuple(uint id, string name, uint voteCount)[])",
    "function getVotes(uint _candidateId) public view returns (uint)",
    "function getCandidate(uint _candidateId) public view returns (tuple(uint id, string name, uint voteCount))",
    "function electionActive() public view returns (bool)",
    "event VoteCast(address indexed voter, uint candidateId)",
    "event ElectionStateChanged(bool isActive)",
    "event CandidateAdded(uint id, string name)"
];

const CONTRACT_ADDRESS = import.meta.env.VITE_CONTRACT_ADDRESS;

export const getEthereumObject = () => window.ethereum;

export const requestAccount = async () => {
    const ethereum = getEthereumObject();
    if (!ethereum) {
        throw new Error("Make sure you have Metamask!");
    }
    const accounts = await ethereum.request({ method: "eth_requestAccounts" });
    return accounts[0];
};

export const getContract = async () => {
    const ethereum = getEthereumObject();
    if (!ethereum) throw new Error("Metamask not found");

    const provider = new ethers.BrowserProvider(ethereum);
    const signer = await provider.getSigner();

    if (!CONTRACT_ADDRESS) throw new Error("Contract address not found in env");

    const contract = new ethers.Contract(CONTRACT_ADDRESS, VotingABI, signer);
    return contract;
};

export const getCandidates = async () => {
    try {
        const contract = await getContract();
        const candidates = await contract.getAllCandidates();
        // Transform struct array to object array if needed
        return candidates.map(c => ({
            id: Number(c.id),
            name: c.name,
            voteCount: Number(c.voteCount)
        }));
    } catch (error) {
        console.error("Error fetching candidates", error);
        return [];
    }
};

export const castVote = async (candidateId) => {
    try {
        const contract = await getContract();
        const tx = await contract.vote(candidateId);
        await tx.wait();
        return tx.hash;
    } catch (error) {
        console.error("Error casting vote", error);
        throw error;
    }
};

export const isElectionActive = async () => {
    try {
        const contract = await getContract();
        const active = await contract.electionActive();
        return active;
    } catch (error) {
        console.error("Error checking election state", error);
        return false;
    }
};
